# Generated by Django 4.1 on 2022-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=800, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок с описанием услуги',
                'verbose_name_plural': 'Блоки с описанием услуги',
            },
        ),
        migrations.CreateModel(
            name='AdvBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, default='', upload_to='', verbose_name='Иконка')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='О чем блок (для себя)')),
                ('text', models.CharField(blank=True, max_length=60, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Рекламный блок',
                'verbose_name_plural': 'Рекламные блоки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Title страницы')),
                ('title_with_image', models.CharField(blank=True, max_length=50, verbose_name='Заголовок на главном фото')),
                ('subtitle_with_image', models.CharField(blank=True, max_length=120, verbose_name='Подзаголовок на фото')),
                ('logo', models.FileField(blank=True, upload_to='', verbose_name='Лого')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Главное фото')),
                ('job_time', models.CharField(blank=True, max_length=50, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Верхняя часть с фото',
                'verbose_name_plural': 'Верхняя часть с фото',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Что ремонтируем?')),
                ('issue', models.CharField(blank=True, max_length=300, verbose_name='Описание проблемы')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Название техники',
                'verbose_name_plural': 'Названия техники',
            },
        ),
    ]
