# Generated by Django 4.1 on 2022-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remont', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Об услуге', 'verbose_name_plural': 'Об услугах'},
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='issue',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_1',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_10',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_2',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_3',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_4',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_5',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_6',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_7',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_8',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='issue_9',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='text_after',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст после перечня поломок'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='text_before',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст до перечня поломок'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='head',
            name='subtitle_with_image',
            field=models.CharField(blank=True, max_length=120, verbose_name='Подзаголовок рядом с фото'),
        ),
        migrations.AlterField(
            model_name='head',
            name='title_with_image',
            field=models.CharField(blank=True, max_length=90, verbose_name='Заголовок рядом с фото'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Что ремонтируем? (для себя)'),
        ),
    ]
