# Generated by Django 4.1 on 2022-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remont', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
            },
        ),
    ]
